prometheus:
  prometheus-pushgateway:
    enabled: false
    prometheus-node-exporter:
      enabled: false
    kube-state-metrics:
      enabled: false
    alertmanager:
      enabled: false
    serverFiles:
      prometheus.yml:
        scrape_configs:
          - job_name: genie
            honor_timestamps: true
            scrape_interval: 15s
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: http
            static_configs:
              - targets:
                  - genie:8080
          - job_name: watcher
            honor_timestamps: true
            scrape_interval: 15s
            scrape_timeout: 10s
            metrics_path: /metrics
            scheme: http
            static_configs:
              - targets:
                  - watcher:8081

endpoints:
  - name: google_bd
    target:
      type: webpage
      endpoint: https://www.google.com.bd/
      interval: 15