prometheus:
  prometheus-pushgateway:
    enabled: false
    prometheus-node-exporter:
      enabled: false
    kube-state-metrics:
      enabled: false
    alertmanager:
      enabled: false

endpoints:
  - name: google_bd
    target:
      type: webpage
      endpoint: https://www.google.com.bd/
      interval: 15