apiVersion: v1
kind: ConfigMap
metadata:
  name: watchpoints
data:
  endpoints.yaml: |-
{{- range .Values.endpoints }}
    - name: {{ .name }}
      target:
        type: {{ .target.type }}
        endpoint: {{ .target.endpoint }}
        interval: {{ .target.interval }}
{{- end }}
