apiVersion: v1
kind: Service
metadata:
  name: genie
spec:
  selector:
    app: genie
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: watcher
spec:
  selector:
    app: watcher
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081